version: '3.8'

services:
  redis:
    image: redis:7.4.5-alpine3.21
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  realtime-db:
    image: postgres:14.18-bookworm
    container_name: realtime-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: shivam2003
      POSTGRES_DB: realtime_app  
    ports:
      - "5432:5432"
    volumes:
      - realtime_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data:
  realtime_db_data:
